# Generated by Django 4.2 on 2023-04-10 10:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('named_url', models.CharField(blank=True, max_length=100)),
                ('level', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
